# Generated by Django 3.0.4 on 2020-06-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0004_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=50)),
                ('doctoremail', models.CharField(max_length=50)),
                ('patientname', models.CharField(max_length=50)),
                ('patientemail', models.CharField(max_length=50)),
                ('appointmentdate', models.CharField(max_length=10)),
                ('appointmenttime', models.CharField(max_length=10)),
                ('symptoms', models.CharField(max_length=100)),
            ],
        ),
    ]
