# Generated by Django 3.0.4 on 2020-06-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0005_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentdate',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmenttime',
            field=models.TimeField(max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctoremail',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientemail',
            field=models.EmailField(max_length=50),
        ),
    ]
