# Generated by Django 3.0.4 on 2020-06-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0006_auto_20200626_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
