# Generated by Django 3.0.4 on 2020-06-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0008_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
